Task 5

NumPy Matrix Operations

In [1]:
num1=np.array([[1,2],[3,4]])
num2=np.array([[5,6],[7,8]])
sum=num1+num2
print(sum)

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

[[ 6  8]
 [10 12]]


In [2]:
dot=num1.dot(num2)
dot

array([[19, 22],
       [43, 50]])

In [3]:
prod=num1*num2
prod

array([[ 5, 12],
       [21, 32]])

In [4]:
mat_prod=num1@num2
mat_prod

array([[19, 22],
       [43, 50]])